# Quaternions als Klasse testen

In [1]:
import numpy as np
from quaternion import Quaternion

In [2]:
q1 = Quaternion.from_axis(30,[0,0.8,0.6])
q1

Quaternion(0.0 i + 0.2070552360820166 j + 0.15529142706151244 k + 0.9659258262890683)

In [3]:
q1.array 

array([0.        , 0.20705524, 0.15529143, 0.96592583])

In [4]:
print(q1.vector) 
print(q1.scalar)

[0.         0.20705524 0.15529143]
0.9659258262890683


In [5]:
q2 = Quaternion.from_axis(45,[0,0,1])
q2

Quaternion(0.0 i + 0.0 j + 0.3826834323650898 k + 0.9238795325112867)

## Multiplikation

Ich komme bei Multiplikation auf das gleiche Ergebnis wie SciPy (siehe unten), bei Ihnen ist bei `QT.Q_mult(q2,q1)` die zweite Zahl im Ergebnisarray -0.079 statt +0.079.

In [6]:
q3 = q1 * q2
q3

Quaternion(0.0792366084330301 i + 0.1912940947154676 j + 0.5131143816509868 k + 0.8329716445077503)

Wird intern gerechnet als dot product:

In [7]:
q1.as_Q() @ q2.array

array([0.07923661, 0.19129409, 0.51311438, 0.83297164])

In [8]:
i = Quaternion(np.array([1,0,0,0]))
j = Quaternion(np.array([0,1,0,0]))
k = Quaternion(np.array([0,0,1,0]))

In [9]:
i * i # -1

Quaternion(0.0 i + 0.0 j + 0.0 k + -1.0)

In [10]:
i * j # k

Quaternion(0.0 i + 0.0 j + 1.0 k + 0.0)

In [11]:
i * j * k # -1

Quaternion(0.0 i + 0.0 j + 0.0 k + -1.0)

## Rotation

In [12]:
point = [1,2,3]

p = Quaternion.from_point(point)
p

Quaternion(1.0 i + 2.0 j + 3.0 k + 0.0)

Rotation: (gleiches Ergebnis wie unten mit Scipy)

In [13]:
p2 = q1 * p * q1.conjugate()
p2.vector

array([1.4660254 , 2.39646171, 2.47138439])

Zurückdrehen

In [14]:
qinv = q1.inv()

q3 = qinv * p2 * qinv.conjugate()
q3.vector

array([1., 2., 3.])

Was gibt $W^\intercal(p) \cdot Q(p) = ?$ 

In [15]:
(q1.as_W().T @ q1.as_Q()).round(8)

array([[ 0.8660254 , -0.3       ,  0.4       , -0.        ],
       [ 0.3       ,  0.95176915,  0.06430781, -0.        ],
       [-0.4       ,  0.06430781,  0.91425626,  0.        ],
       [ 0.        , -0.        ,  0.        ,  1.        ]])

In [16]:
q1.as_matrix()

array([[ 0.8660254 , -0.3       ,  0.4       ],
       [ 0.3       ,  0.95176915,  0.06430781],
       [-0.4       ,  0.06430781,  0.91425626]])

In [17]:
q1.as_Q()

array([[ 0.96592583, -0.15529143,  0.20705524,  0.        ],
       [ 0.15529143,  0.96592583,  0.        ,  0.20705524],
       [-0.20705524,  0.        ,  0.96592583,  0.15529143],
       [-0.        , -0.20705524, -0.15529143,  0.96592583]])

## Vergleich mit Scipy Rotaton

In [18]:
from scipy.spatial.transform import Rotation as R

In [19]:
r1 = R.from_quat(q1.array)
r2 = R.from_quat(q2.array)

In [20]:
r1.as_matrix()

array([[ 0.8660254 , -0.3       ,  0.4       ],
       [ 0.3       ,  0.95176915,  0.06430781],
       [-0.4       ,  0.06430781,  0.91425626]])

In [21]:
r3 = r1 * r2 
r3.as_quat()

array([0.07923661, 0.19129409, 0.51311438, 0.83297164])

In [22]:
r1.apply(point)

array([1.4660254 , 2.39646171, 2.47138439])